CREATE TABLE IF NOT EXISTS Games(
	Id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	Name TEXT NOT NULL,
	CompletionPercent REAL NOT NULL,
	IsActivelyPlaying TINYINT NOT NULL,
	IsPersistent TINYINT NOT NULL,
	Rating REAL,
	GiantBombId INTEGER,
	GiantBombUrl INTEGER,
	SteamId TEXT,
	ThumbnailImageUrl TEXT,
	MediumImageUrl TEXT,
	LastUpdated DATETIME
);
CREATE INDEX games_name ON Games(Name);

CREATE TABLE IF NOT EXISTS Categories(
	Id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	Name TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS GameCategories(
	GameId INTEGER NOT NULL,
	CategoryId INTEGER NOT NULL,
	PRIMARY KEY(GameId, CategoryId)
	FOREIGN KEY(GameId) REFERENCES Games(Id)
	FOREIGN KEY(CategoryId) REFERENCES Category(Id)
);
